### ISSUE TITLE
在下界下线后再次上线无法登录

### ISSUE THREAD

**Issue by SERNNNN** [CatSeed/CatSeedLogin#11]
当在下界下线后再次上线登录时会提示无法发送聊天信息，同时出生点附近一定区域内的地形会被替换成下界的地形。具体情况如下图，在删除登录插件后问题消失。
希望可以直接在上次退出的地点登录
![屏幕截图 2021-11-20 224150](https://i0.hdslb.com/bfs/album/c565d1a943c220067401c89f7c9fa18286ce6fa8.png@518w.webp)
![屏幕截图 2021-11-20 224604](https://user-images.githubusercontent.com/30836444/142730788-69d4ae47-c5b7-45e7-8e33-c4ac0fb01ac5.png)

![屏幕截图 2021-11-20 224619](https://user-images.githubusercontent.com/30836444/142730798-1b27cdb5-1b47-4343-ba17-05d9a654c381.png)

**Comment by CatSeed** [comment]
感觉这不是我插件造成的问题呀。。。

**Comment by SERNNNN** [comment]
但是当时我测试了发现把登陆插件删掉之后就能正常登录，而且世界没有错误。不清楚是哪的问题。。。不过现在那个服务器也已经不运行了
